spring.application.name=PhoneStore
server.port=8080

# MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/phone_store?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8&useUnicode=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT (replace in production)
app.jwt.secret=BJ4AFOGtNDKL9EUTA8STcRRGU2vyrwxi/zrTdMt8Zxk23JIZOglbakoC/qiYWb/+HJcGgc4lq9dGnZ6NmFIy0Q==
app.jwt.expiration-ms=86400000

# Cloudinary
cloudinary.cloud-name=dozpywcus
cloudinary.api-key=345466748819321
cloudinary.api-secret=hX6w0WmgPjD1ffxaDXs69QUjiDQ

# Logging
logging.level.root=INFO
logging.level.com.tmdt.phone_store_backend=DEBUG

# Spring Security
spring.security.user.name=admin
spring.security.user.password=admin123

# Error handling
server.error.include-message=always
server.error.include-binding-errors=always

# Email (SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nguyenvanhoang272004@gmail.com
spring.mail.password=idnb jpve udgk eqdp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# PayOS Configuration
payos.client-id=8c54e89e-8f9a-4499-a495-b540b53a0b06
payos.api-key=8f014b50-fa22-4978-b9a6-7c95cac38cd9
payos.checksum-key=4e883b1f48b6e779934a7141ee49b89d96b01c3396a8f9e73ea347056e7b5d0f

# App config
app.frontend.url=http://localhost:5173

# Groq api key
# Groq AI (thay thế Gemini)
app.groq.model=llama-3.3-70b-versatile
app.groq.api-key={API_Key}


# ChromaDB Configuration
chromadb.host=localhost
chromadb.port=8000

# AI Configuration
app.ai.embedding.model=embedding-001
app.ai.embedding.dimension=768
app.ai.chat.max-tokens=2048
app.ai.chat.temperature=0.7

# RAG Configuration
app.rag.product.top-k=5
app.rag.faq.top-k=3
app.rag.memory.turns=10

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id={client-id}
spring.security.oauth2.client.registration.google.client-secret={Client-secret}

spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

