spring.application.name=PhoneStore
server.port=8080

# MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/phone_store?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT (replace in production)
app.jwt.secret=BJ4AFOGtNDKL9EUTA8STcRRGU2vyrwxi/zrTdMt8Zxk23JIZOglbakoC/qiYWb/+HJcGgc4lq9dGnZ6NmFIy0Q==
app.jwt.expiration-ms=86400000

# Logging
logging.level.root=INFO
logging.level.com.tmdt.phone_store_backend=DEBUG

# Spring Security
spring.security.user.name=admin
spring.security.user.password=admin123

# Error handling
server.error.include-message=always
server.error.include-binding-errors=always
