spring.application.name=PhoneStore

# MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/phone_store?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT (replace in production)
app.jwt.secret=RjNwWmxYVE03VnV6S0J5Z0N4R2hMZ2s2Tm1nU1hOWnA1Q0pRWG1EakY3bA==
app.jwt.expiration-ms=86400000
